modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "${mod_issues}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
description = '''${mod_description}'''
logoFile = "icon.png"
authors = "${mod_author}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange="[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "CLIENT"